### ISSUE TITLE
Feature request: additional flags on units

### ISSUE THREAD

**Issue by nschneid** [omriabnd/UCCA-App#10]
In addition to the Comment field, I propose:

* a binary `?` flag that indicates the annotator's uncertainty about the category; typically the uncertainty will be explained in the `Comment` field
* a binary `!` flag that indicates some sort of problem, e.g. with an upstream annotation
* a short text field called `Cluster` which allows for an informal description grouping the unit with other similar ones in the corpus

These are pieces of information that we already have for our STREUSLE data, so we will want to be able to import this into UCCA-App.

**Comment by nschneid** [comment]
(This solution would essentially mean all functionality supported by the old STREUSLE annotation tool, nanni, can be replaced by UCCA-App. One small feature that it does not cover is support for multiple tentative tags, like `Topic,Stimulus?`, but these can be moved to the Comment field in combination with the `?` flag.)

**Comment by nschneid** [comment]
TBD: If a unit has no categories but the `?` or `!` flag is set, is it considered submittable?

**Comment by omriabnd** [comment]
Re the '?' and '!' tags: the functionality intended for this is the default categories. Every unit can be set to be default. If it is default at the time a layer is created, it is considered a default category for the layer. This means that it is not counted as meeting the at-least-one-category-per-unit constraint. (there's a bug there we need to fix, but that's what it means)

Re Cluster: why is the unit-level comment not applicable for this? is Cluster essentially another free text field for each unit? or am I missing something?

**Comment by nschneid** [comment]
Perhaps I don't quite understand the concept of default categories and how they interact with slots. The motivation for `?` as a flag rather than category is to combine it with a tentative category or pair of slotted categories.

> Re Cluster: why is the unit-level comment not applicable for this? is Cluster essentially another free text field for each unit? or am I missing something?

Yeah, another free text field. Comment is intended for remarks specific to the token, Cluster for a string that groups it with other tokens

**Comment by omriabnd** [comment]
Re default categories: OK, so this can be accomplished by not assigning default categories one of the two slots. This is already happening with derived layers: the categories assigned by the parent task do not take up either of the two slots.

Re cluster: OK.

**Comment by nschneid** [comment]
(Can we come up with a better term than "default" category? That makes it sound like it's present unless another category is chosen. Maybe an "ancillary" category?)

**Comment by omriabnd** [comment]
nice. how about 'utility category' or 'system category'? (maybe yours is
better; not sure)

**Comment by nschneid** [comment]
"meta-category"?

**Comment by omriabnd** [comment]
OK
