### ISSUE TITLE
Best way to define supersenses layer?

### ISSUE THREAD

**Issue by jakpra** [omriabnd/UCCA-App#13]
I want to have all the preposition supersense labels as a possible refinements for both "Adpositional Expression (weak)" and "Adpositional Expression (strong)". That means that every refinement category should be able to be the child of more than one root category. I was trying to do this with a refinement layer, but maybe a coarsening layer is better choice? What are the intended use cases for refinement/coarsening layers?

Anyways, when I try to submit a refinement layer as described above I get the following errors:

vendor-99fa155520.js:25464 PUT http://ucca.development.cs.huji.ac.il/api/v1/layers/67/ 500 (Internal Server Error)
(anonymous) @ vendor-99fa155520.js:25464
sendReq @ vendor-99fa155520.js:25257
serverRequest @ vendor-99fa155520.js:24967
processQueue @ vendor-99fa155520.js:29538
(anonymous) @ vendor-99fa155520.js:29554
$eval @ vendor-99fa155520.js:30800
$digest @ vendor-99fa155520.js:30616
$apply @ vendor-99fa155520.js:30908
(anonymous) @ vendor-99fa155520.js:47300
dispatch @ vendor-99fa155520.js:4435
elemData.handle @ vendor-99fa155520.js:4121

vendor-99fa155520.js:27224 {data: "IntegrityError at /api/v1/layers/67/↵duplicate key… generated by the handler for this status code.↵↵", status: 500, config: {…}, statusText: "Internal Server Error", headers: ƒ}

**Comment by omriabnd** [comment]
I will put a better error message.
