### ISSUE TITLE
Bug with slotted layers?

### ISSUE THREAD

**Issue by jakpra** [omriabnd/UCCA-App#16]
I created the refinement layer (supersenses) as a slotted layer, but it looks like the first slot is already occupied by the root layer (MWE) category and thus we remain with only one slot for the refinement layer (supersenses). Is that intentional? Am I doing something wrong?

Cf. Annotation Tasks 621, 620, 619, refinement layer 67, root layer 64, refinement project 80.

**Comment by omriabnd** [comment]
That sounds like a bug. Let me check.

**Comment by nschneid** [comment]
Should the fix show up in existing tasks, or do we need to create new ones?

**Comment by omriabnd** [comment]
You can use the same tasks, just empty your cache.


בתאריך 3 בנוב׳ 2017 02:35 PM,‏ "Nathan Schneider" <notifications@github.com>
כתב:

**Comment by nschneid** [comment]
I see, the supercategory label still shows up on the unit, but doesn't count toward the 2 slots.

Is it possible to hide the supercategory label, as it's visually distracting, and only show units with a relevant supercategory? In the case of preposition supersenses there is only one relevant supercategory for the refinement layer.

**Comment by omriabnd** [comment]
I wouldn't remove it, as if it is a refinement layer, you need to know which is the supercategory in order to know what the sub-categories are. How about having them faded? 

(btw, do you happen to know how to actually do it in AngularJS?)

**Comment by nschneid** [comment]
Can a refinement layer ever have multiple supercategories being refined? If not, why not just show those units?

To display the supercategories in a deemphasized way, perhaps just making them gray text without a colored background. Likewise, for the display of the document at the top, perhaps show all the units without refined categories as gray boxes. That way colors are reserved for the refinement categories actually relevant to the present layer.

(No, I don't know any Angular JS.)

**Comment by omriabnd** [comment]
A layer may have several supercategories being refined.

OK, I'll add it to the TODO.

**Comment by nschneid** [comment]
I would also suggest that units not relevant to the refinement layer (i.e. labeled with a category not being refined) are hidden or deemphasized somehow.

BTW, it may take a few iterations of trial and error before we get these sorts of UI decisions right. Hard to envision exactly what we need without trying it.

**Comment by omriabnd** [comment]
OK

**Comment by omriabnd** [comment]
➤ omriabnd commented:

covered by other issues
