### ISSUE TITLE
Remove the Client/release folder from git

### ISSUE THREAD

**Issue by zmbq** [omriabnd/UCCA-App#26]
It's ignored by Client/.gitignore and shouldn't be there.

**Comment by omriabnd** [comment]
The idea was that users that do not wish to install gulp, bower etc. can just use the Client/release out of the box. Do you have another suggestion to support this?

**Comment by zmbq** [comment]
If the release folder is important, it shouldn't be in .gitignore (PyCharm tried to delete its entire content automatically because of it. That's how I found out there's a contradiction).

As for easier deployment, I have a few ideas but they don't belong in this issue (we'll never find them here).

So for now I'm just fixing .gitignore so it doesn't ignore the release folder, and we'll worry about simpler deployment later.
