### ISSUE TITLE
Issue #19: only check restriction for unit in slot 1 if the category is a refined one (in a refinement layer)

### ISSUE THREAD

**Issue by omriabnd** [omriabnd/UCCA-App#37]

**Comment by omriabnd** [comment]
➤ Jakob Prange commented:

commit 32b75177965e3f67041f485b17cab50c47bcf576

**Comment by omriabnd** [comment]
➤ omriabnd commented:

Jakob, I tried starting a new task in project #80 and I see that the parent categories are not displayed at all. Did you disable them?

**Comment by omriabnd** [comment]
➤ Jakob Prange commented:

Yes, I tried to unclutter the annotation page for refinement projects.

**Comment by omriabnd** [comment]
➤ Jakob Prange commented:

But I also think this is not optimal for refinements where more than one category is being refined.

**Comment by omriabnd** [comment]
➤ omriabnd commented:

Could you put the parent categories back in but put them faded?

**Comment by nschneid** [comment]
Maybe there should be a toggle in the UI to show or hide all parent categories.

**Comment by omriabnd** [comment]
Sounds like a good idea.


בתאריך 2 בדצמ׳ 2017 09:46 PM,‏ "Nathan Schneider" <notifications@github.com>
כתב:

**Comment by omriabnd** [comment]
➤ omriabnd commented:

I changed the filterForRelevance for now to being always true.
