### ISSUE TITLE
Each token may have a pre-defined list of categories (dictionary of strings --> category lists), and the left sidebar would show the categories in that order

### ISSUE THREAD

**Issue by omriabnd** [omriabnd/UCCA-App#52]
-- Categories not in the list would be shown below the ones that are, in alphabetical order. 
-- Example: {"in": ["Locus", "Time", "Interval"], "out of": ["Source", "Locus", "Explanation"]}

**Comment by omriabnd** [comment]
➤ Jakob Prange commented:

commit 32b75177965e3f67041f485b17cab50c47bcf576

**Comment by omriabnd** [comment]
➤ omriabnd commented:

Jakob, currently the categories are not shown at all in a non-refinement layer

**Comment by jakpra** [comment]
For me, every  category that should be shown is shown, also in non-refinement layers. Can you send a screenshot and/or a more detailed description of what you're missing?

**Comment by omriabnd** [comment]
➤ omriabnd commented:

Works on my machine.
