### ISSUE TITLE
Can't save/submit tokenization task

### ISSUE THREAD

**Issue by jakpra** [omriabnd/UCCA-App#7]
Whenever I want to save or submit a tokenization task, I get the following error message:
```
Pay Attention!!!
Bad Request: This field may not be blank.: user_comment
```
But the button for adding a user comment is gone (it was still there last week).

**Comment by omriabnd** [comment]
I think I fix it.
Note that user_comment does appear for annotation tasks, but not for tokenization tasks. We'll add it there as well.
